# -*- coding: utf-8 -*-
# Generated by Django 1.11.14 on 2018-07-19 10:52
from __future__ import unicode_literals

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='tweet',
            name='date_and_time',
            field=models.DateTimeField(default=datetime.datetime.now),
        ),
    ]
