# -*- coding: utf-8 -*-
# Generated by Django 1.11.14 on 2018-07-20 11:33
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0002_auto_20180719_1052'),
    ]

    operations = [
        migrations.CreateModel(
            name='Tweet_Interaction',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('like', models.IntegerField(default=0)),
                ('retweet', models.IntegerField(default=0)),
                ('tweet', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='app.Tweet')),
            ],
        ),
    ]
