# -*- coding: utf-8 -*-
# Generated by Django 1.11.14 on 2018-08-16 19:45
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0003_tweet_interaction'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='tweet_interaction',
            name='tweet',
        ),
        migrations.DeleteModel(
            name='Tweet_Interaction',
        ),
    ]
